### ISSUE TITLE
File missing: sentences_aggregated_50-449.csv

### ISSUE THREAD

**Issue by Henri-Lo** [cle-ment/pycon-finland-2016-talk#1]
Hello,
it seems that this file is missing: 

df = pd.read_csv("/Users/cwestrup/thesis/data/collected/crowdflower/data/sentences_aggregated_50-449.csv")

Or is it in some other repo?

**Comment by cle-ment** [comment]
Hey! Thanks for asking, I agreed with the company that I could give out the collected data on request so I sent you an email with the data and some explanations.

If anyone else comes across this, just send me a message.
